name: "TMC2130 Pen/Laser/Sandtable"
board: "TMC2130 Pen/Laser/Sandtable"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

kinematics:
  corexy:

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 3200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 350
    soft_limits: false
    hard_limits: false

    homing:
      allow_single_axis: true
      cycle: 2
      pulloff_mm: 5
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: gpio.32:low:pu
      tmc_2130:
        direction_pin: gpio.26
        step_pin: gpio.12
        cs_pin: gpio.17
        r_sense_ohms: 0.110
        run_amps: 0.50
        hold_amps: 0.250
        microsteps: 128
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
    motor1:
      null_motor:

  y:
    steps_per_mm: 3200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 350
    soft_limits: false
    homing:
      allow_single_axis: true
      cycle: 1
      pulloff_mm: 5
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.4:low:pu
      tmc_2130:
        direction_pin: gpio.25
        step_pin: gpio.14
        cs_pin: gpio.16
        r_sense_ohms: 0.110
        run_amps: 0.50
        hold_amps: 0.250
        microsteps: 128
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

probe:
  pin: NO_PIN

coolant:
  flood: NO_PIN
  mist:  NO_PIN

start:
  must_home: true
